language: node_js
node_js:
  - '22' # Specify the Node.js version

services:
  - postgresql # Use PostgreSQL service

before_install:
  - npm install -g yarn # Install Yarn globally

install:
  - yarn install # Install dependencies

before_script:
  - psql -c 'CREATE DATABASE test_db;' -U postgres # Create a test database
  - psql -c 'CREATE DATABASE test_e2e_db;' -U postgres # Create a separate database for e2e tests

script:
  - yarn lint # Lint the code
  - yarn build # Build the project
  - yarn test # Run unit tests
  - yarn test:e2e # Run end-to-end tests

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: build
      script: yarn build
    - stage: test
      script: yarn test
    - stage: test:e2e
      script: yarn test:e2e

env:
  global:
    - DATABASE_URL=postgres://postgres@localhost:5432/test_db # Set the database URL for unit testing
    - E2E_DATABASE_URL=postgres://postgres@localhost:5432/test_e2e_db # Set the database URL for e2e testing

cache:
  yarn: true
  directories:
    - node_modules # Cache node_modules for faster builds

notifications:
  email: false # Disable email notifications (optional)
