name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: local
          POSTGRES_PASSWORD: local
          POSTGRES_DB: local
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U local -d local -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            if PGPASSWORD=local psql -h localhost -U local -p 5432 -c '\q'; then
              echo "Postgres is up and running"
              break
            fi
            echo "Waiting for Postgres to be ready..."
            sleep 2
          done

      - name: Create E2E test database
        run: |
          PGPASSWORD=local psql -h localhost -U local -p 5432 -c 'CREATE DATABASE test_e2e_db;'

      - name: Run migrations on E2E test database
        run: DATABASE_URL=postgres://local:local@localhost:5432/test_e2e_db yarn migration:run

      - name: Seed E2E test database
        run: |
          PGPASSWORD=local psql -h localhost -U local -p 5432 -d test_e2e_db -f ./src/seed/seed.sql

      - name: Lint codebase
        run: yarn lint

      - name: Build the project
        run: yarn build

      - name: Run unit tests
        run: yarn test

      - name: Run E2E tests
        run: yarn test:e2e

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
