name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: local
          POSTGRES_PASSWORD: local
          POSTGRES_DB: local
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://local:local@localhost:5432/local
      E2E_DATABASE_URL: postgres://local:local@localhost:5432/test_e2e_db
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
      POSTGRES_E2E_DB: test_e2e_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Create E2E test database
        env:
          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: psql -h localhost -U ${{ env.POSTGRES_USER }} -c 'CREATE DATABASE test_e2e_db;'

      - name: Lint codebase
        run: yarn lint

      - name: Build the project
        run: yarn build

      - name: Run unit tests
        run: yarn test

      - name: Run E2E tests
        run: yarn test:e2e

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
