name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: local
          POSTGRES_PASSWORD: local
          POSTGRES_DB: local
        ports:
          - 5432:5432
          - 5445:5445
        options: >-
          --health-cmd="pg_isready -d local"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Upload seed.sql file
        uses: actions/upload-artifact@v3
        with:
          name: seed-file
          path: ./src/seed/seed.sql

      - name: Create E2E test database
        run: |
          PGPASSWORD=${{ env.POSTGRES_PASSWORD }} psql -h localhost -U ${{ env.POSTGRES_USER }} -p 5445 -c 'CREATE DATABASE test_e2e_db;'

      - name: Run migrations on E2E test database
        run: |
          yarn migration:run -d src/data-source/data-source.test.ts

      - name: Seed E2E test database
        run: |
          PGPASSWORD=${{ env.POSTGRES_PASSWORD }} psql -h localhost -U ${{ env.POSTGRES_USER }} -p 5445 -d test_e2e_db -f ./src/seed/seed.sql

      - name: Lint codebase
        run: yarn lint

      - name: Build the project
        run: yarn build

      - name: Run unit tests
        run: yarn test

      - name: Run E2E tests
        run: yarn test:e2e

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
